/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.game.view;

import java.awt.event.ActionListener;
/**
 *
 * @author danar
 */
public class FrameHistory extends javax.swing.JFrame {

    /**
     * Creates new form FrameHistory
     */
    public FrameHistory() {
        initComponents();
    }
    
    public void setController(ActionListener controller){
        this.btnReturnMenu.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReturnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonVolverMenu.png"))); // NOI18N
        btnReturnMenu.setActionCommand("volverMenu");
        getContentPane().add(btnReturnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 190, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Historia.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 795));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main (String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameHistory().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
