/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.game.view;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author danar
 */
public class JugarFrame extends javax.swing.JFrame {
    
//    private ImageIcon corazon1,corazon2,corazon3;
    private JLabel lblVidas, lblTimer;
    private Timer timer;
    private int tiempo = 120;
    

    /**
     * Creates new form JugarFrame
     */
    public JugarFrame() {
        initComponents();
        
        panelJugar1.setPanelJugar(this);
        this.setLocationRelativeTo(null);
        panelJugar1.iniciarHilo();
        
        labelTiempo.setText("Tiempo: " + tiempo);
        labelTiempo.setFont(new java.awt.Font("Candara", 1, 15));
        labelVidas.setText("Vida: " + panelJugar1.getVidasPersonaje() + "/ 3");
        labelVidas.setFont(new java.awt.Font("Candara", 1, 18));

        iniciarTimer();
        
        corazonLabel1.setVisible(true);
        corazonLabel2.setVisible(true);
        corazonLabel3.setVisible(true);
    }
    
    public void setController(ActionListener controller){
        this.btnVolverMenu.addActionListener(controller);
        this.btnReiniciar.addActionListener(controller);
        this.btnPausa.addActionListener(controller);
    }
    
    public PanelJugar getPanel(){
        return panelJugar1;
    }
    
    public void iniciarTimer() {
        tiempo=120;
        timer = new Timer(1000, e -> { //Se mide en milisegundos
        tiempo=tiempo-1; //es decir, cada segundo el timer va a reducir en 1(1 segundo menos)
        labelTiempo.setText("Tiempo: " + tiempo);
        mostrarObjetos();
        if (tiempo <= 0) {
            timer.stop();
            JOptionPane.showMessageDialog(this, new ImageIcon("./src/main/resources/pantallaTimeOut.png"));
            reiniciarJuego();
            }
        });
        timer.start();
    }
    
    public void pausarJuego() {  //Si al presionarlo, el tiempo esta coriendo, se detiene. Si el tiempo ya esta detenido, vuelve a correr
        if (timer.isRunning()) {
            timer.stop();
        } else {
            timer.restart();
        }
    }
    
    public void listenKey(KeyListener listen){
        this.addKeyListener(listen);
    }
    
    public void reiniciarJuego() {
        panelJugar1.reiniciar();
        tiempo = 120;
        labelVidas.setText("Vida: " + panelJugar1.getVidasPersonaje() + "/ 3");
        labelTiempo.setText("Tiempo: " + tiempo);
        timer.restart();
    }
    
    public void actualizarVidas(int vidas) {  //Recive por parametros la cantidad de vidas para poder mostrarlas
        labelVidas.setText("Vida: " + panelJugar1.getVidasPersonaje() + "/ 3");
    }
    
    public void mostrarObjetos(){  //Muestra los corazones que hemos recolectado
        
        if(panelJugar1.getObjetosRecolectados()!=0){
            if(panelJugar1.getObjetosRecolectados()==1){
            
            corazonLabel1.setVisible(true);
            corazonLabel2.setVisible(false);
            corazonLabel3.setVisible(false);
            }
            if(panelJugar1.getObjetosRecolectados()==2){
                corazonLabel1.setVisible(true);
                corazonLabel2.setVisible(true);
                corazonLabel3.setVisible(false);
            }
            if(panelJugar1.getObjetosRecolectados()>=3){
                corazonLabel1.setVisible(true);
                corazonLabel2.setVisible(true);
                corazonLabel3.setVisible(true);
            }
        } else {
            corazonLabel1.setVisible(false);
            corazonLabel2.setVisible(false);
            corazonLabel3.setVisible(false);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolverMenu = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        corazonLabel3 = new javax.swing.JLabel();
        corazonLabel2 = new javax.swing.JLabel();
        corazonLabel1 = new javax.swing.JLabel();
        labelVidas = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();
        panelJugar1 = new ucr.ac.cr.tm2100.g3.game.view.PanelJugar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laberinto 2024-Final-ButtonVolverMenu.png"))); // NOI18N
        btnVolverMenu.setActionCommand("volverMenu");
        getContentPane().add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, 210, 80));

        btnPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonPausa.png"))); // NOI18N
        btnPausa.setActionCommand("Pausa");
        getContentPane().add(btnPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 120, 50));

        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonReiniciar.png"))); // NOI18N
        btnReiniciar.setActionCommand("Reiniciar");
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 150, 40));

        corazonLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CorazonFrame.png"))); // NOI18N
        getContentPane().add(corazonLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 218, -1, -1));

        corazonLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CorazonFrame.png"))); // NOI18N
        getContentPane().add(corazonLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 216, -1, -1));

        corazonLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CorazonFrame.png"))); // NOI18N
        getContentPane().add(corazonLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 212, 50, 50));
        getContentPane().add(labelVidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, 150, 60));
        getContentPane().add(labelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 160, 50));

        panelJugar1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout panelJugar1Layout = new javax.swing.GroupLayout(panelJugar1);
        panelJugar1.setLayout(panelJugar1Layout);
        panelJugar1Layout.setHorizontalGroup(
            panelJugar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        panelJugar1Layout.setVerticalGroup(
            panelJugar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(panelJugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 680, 680));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaFinalProgra.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main (String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JugarFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel corazonLabel1;
    private javax.swing.JLabel corazonLabel2;
    private javax.swing.JLabel corazonLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JLabel labelVidas;
    private ucr.ac.cr.tm2100.g3.game.view.PanelJugar panelJugar1;
    // End of variables declaration//GEN-END:variables
}
